import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrincipalLayout from "@/components/layouts/PrincipalLayout";
import Provider from "@/providers/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Provider>
          <PrincipalLayout>{children}</PrincipalLayout>
        </Provider>
      </body>
    </html>
  );
}
